### ISSUE TITLE
SDGB 1.50 面板样式丢失

### ISSUE THREAD

**Issue by misakanetwork2018** [WYH2004-MC/Sinmai-Assist#10]
**描述错误**  
进入扫码界面后，面板按钮样式丢失

**重现步骤**  
重现此问题的步骤：  
1. 按下任意按键或投币进入扫码登录界面
2. 出现样式丢失现象

**截图**  
![Image](https://github.com/user-attachments/assets/bce254d1-2988-46a0-bedd-e5a5c551db72)
![Image](https://github.com/user-attachments/assets/433b9f59-a749-4e00-a457-3c43a52ef4f1)

**Sinmai-Assist 配置文件**  
```
common:
  unityLogger:
    enable: false
    printToConsole: true
  infinityTimer: false
  infinityTimerLegacy: false
  disableMask: false
  disableBackground: false
  showFPS: false
  forceQuickRetry: false
  forwardATouchRegionToButton: false
  skipFade: false
  skipWarningScreen: false
  quickBoot: false
  blockCoin: false
  ignoreAnyGameInformation: false
  changeDefaultOption: false
  changeFadeStyle: false
  singlePlayer:
    enable: false
    hideSubMonitor: false
  networkLogger:
    enable: true
    printToConsole: false
  customVersionText:
    enable: false
    versionText: Sinmai-Assist
  dummyLogin:
    enable: false
    defaultUserId: 0
  customCameraId:
    enable: false
    chimeCameraId: 0
    leftQrCameraId: 0
    rightQrCameraId: 0
    photoCameraId: 0
  changeGameSettings:
    enable: false
    codeRead: false
    iconPhoto: false
    uploadPhoto: false
    charaSelect: false
cheat:
  autoPlay: true
  fastSkip: false
  chartController: false
  allCollection: false
  unlockEvent: false
  unlockMusic: false
  unlockMaster: false
  unlockUtage:
    enable: false
    unlockDoublePlayerMusic: false
  saveUnlockMusic: false
  saveUnlockMaster: false
  resetLoginBonusRecord: false
  forceCurrentIsBest: false
  setAllCharacterAsSameAndLock: false
  rewriteLoginBonusStamp:
    enable: false
    point: 0
fix:
  disableEnvironmentCheck: true
  disableEncryption: false
  disableReboot: true
  disableIniClear: true
  fixCheckAuth: false
  forceAsServer: false
  skipCakeHashCheck: false
  skipSpecialNumCheck: true
  skipVersionCheck: false
  restoreCertificateValidation: false
  rewriteNoteJudgeTiming:
    enable: false
    adjustTiming: 0
    judgeTiming: 0
modSetting:
  showInfo: false
  showPanel: true
  safeMode: false
```

**环境信息：**  
- MelonLoader 版本：0.6.4 
- 游戏版本：SDGB 1.50
- 游戏数据版本：1.50.1
- 连接的服务器：None 
- 安装的 mod：Sinmai-Assist、AquaMai

**其他信息**  
尝试移除AquaMai，但依旧出现该现象
